server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/remember_words?useUnicode=true;characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: abc123
